# Generated by Django 4.1.5 on 2023-03-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categria',
            new_name='Categoria',
        ),
    ]
