# Generated by Django 4.1.5 on 2023-03-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppServicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=300),
        ),
    ]
